russelljimmies-introduction.md
Introduction for William Lemire
=> Fixes #17 : Introduction William Lemire

russelljimmies-introduction.md
Pull request exercise for William Lemire
=> Fixes #7 : Introduction William Lemire

JolanThomassin-introduction.md
Fixes #19, introduction Jolan Thomassin
=> Fixes #19: Introduction Jolan Thomassin

Development-Environment-Setup-Guide/DEV-ENV-SETUP.md
#22
issue22-removed-python-configuration
I removed python configuration from the guide to keep it general.
Closes #22
=> issue #22: removed language specific configuration

melanie-fressard-introduction.md
Fixes #21 : Creation of the melanie-fressard-introduction file
=> Fixes #21 : Introduction Mélanie Fressard

Naming-Conventions/NAMING-RESOURCES.md, README.md
#30
issue30-naming-conventions
added general convention and example for usual CLI accessible resources
Closes #30
=> issue #30: documented naming convention

DevOps-documentation/devops-intake.md
Created an intake file checklist which helps keep track of progress of products as well as making sure necessary files are present
=> Fixes #37 : Add an Intake list template for products

README.md, adr/001-ailab-using-adr-template.fr-ca.md, adr/001-ailab-using-adr-template.md, adr/001-ailab-using-adr.fr-ca.md, adr/001-ailab-using-adr.md, adr/index.md
Closes #41 - Write an ADR on why we decided to use ADRs
Closes #55 - Create an empty template to ease the ADR creation process
=> issue #41: ADR for adopting ADRs

adr/006-database-change-management.md
=> Issue #43 - Write an ADR on our choices of database change management

README.md, TRAINING.md
closes issue #58 
* copy over list of public links from internal wiki
* tweak content to split into sections
=> issue #58: Create TRAINING.md and import internal wiki content

TRAINING.md
=> Update training for new developers with estimated time and fix broken links

adr/index.md
issue #45 you said it didn't work, but that's because you put ```/``` referring the root of the URI. if you leave off the directory entirely it works.
=> Test filename reference without any path specified

adr/008-naming-convention.md
Name: dev-rel-docs/adr/008-naming-convention.md
Start point: [dev-rel-docs/Naming-Conventions/NAMING-RESOURCES.md at main · ai-cfia/dev-rel-docs (github.com)](https://github.com/ai-cfia/dev-rel-docs/blob/main/Naming-Conventions/NAMING-RESOURCES.md)
=> Issue#75 Write an ADR (008) about naming convention

TypeScript-React-Setup-Guide/REACTSETUP.md
- Revise the README to guide through setting up a React app using Vite with TypeScript and SWC.
- Enhance instructions for integrating ESLint and Prettier.
- Add a detailed Table of Contents for improved navigation.
- Include specific steps for configuring ESLint and Prettier, along with creating necessary configuration files.
- Outline the advantages of using Vite and SWC over traditional setups like create-react-app.
- Update installation and prerequisite instructions to reflect the new technology stack.
- Ensure the documentation is clear and concise, aiding in efficient setup and configuration for users.
=> Update README for TypeScript + SWC React App Setup with Vite

TRAINING.md
Throughout Jonathan Lopez's onboarding, it was noticed that there was room for enhancement in the availability of security training resources.
- The training should equip the developer with the skills necessary to work within the AI LAB's framework.
- The training should provide accurate time estimates for each module.
- Closes #101
=> Issue #101: Onboarding process of Jonathan Lopez

TRAINING.md
Explain draft pull request
1. Open an [issue]((https://github.com/ai-cfia/dev-rel-docs/issues)
2. Name it "onboarding process of your name"
3. Use this template:
```
Maxence Guindon onboarding process
Tasks:
Acceptance Criteria:
The training should equip the developer with the skills necessary to work within the AI LAB's framework.
The training should provide accurate time estimates for each module.
```
4. Go back on training.md and click edit button on this file 
5. Edit the document (example add the time it took you to read value and ethics)
6. Click on commit changes
7. create a branch with this format: issue_number-onboarding-process-your-name (example 42-onboarding-process-happy-gilmor)
8. Click on propose change
9.  On the "Open a pull request" page:
10. Add a title
11. Select draft …
=> Explain draft pull request

post-mortems/incident-1.md, postmortems/incident-1.md
- Post mortem write up that occured yesterday
=> issue #98: Started writing post-mortems

adr/008-naming-convention.md
=> Issue #118: Added column into DB naming with examples

TypeScript-AutomatedTesting/AUTOMATED-TESTING-SETUP.md
- Created TypeScript-AutomatedTesting.md with comprehensive guidelines on setting up Vitest and @testing-library/react.
- Included detailed instructions for configuring vitest.config.ts and src/setupTests.ts.
- Outlined steps for writing robust unit tests for React components.
- Described best practices for structuring tests, performing assertions, and handling user interactions.
=> Added documentation for setting up automated tests in TypeScript projects.

Development-Environment-Setup-Guide/DEV-ENV-SETUP.fr-ca.md, Development-Environment-Setup-Guide/DEV-ENV-SETUP.md, Minimal-Backend-Setup-Guides/PYTHON-BACKEND-SETUP.fr-ca.md, README.fr-ca.md, TRAINING.fr-ca.md, TypeScript-AppVersion/APPVERSION-SETUP.fr-ca.md, TypeScript-EnvironmentVariables/ENVIRONMENT-VARIABLES-SETUP.fr-ca.md, TypeScript-React-Setup-Guide/REACTSETUP.fr-ca.md, adr/001-ailab-using-adr-template.fr-ca.md, adr/001-ailab-using-adr.fr-ca.md, adr/008-naming-convention.fr-ca.md, adr/index.fr-ca.md, training/python/handling-exception-training.fr-ca.md
This pull request includes several commits that add French translations to README.md and every md linked to this README.md.
Also, in the french version, the french inclusive language is used.
=> Add French translations 

Development-Environment-Setup-Guide/DEV-ENV-SETUP.md, TRAINING.fr-ca.md, TRAINING.md, adr/019-python-web-framework.en-ca.md, adr/019-python-web-framework.fr-ca.md
An ADR detailing the decision process of the next web framework used in the [fertiscan-backend](https://github.com/ai-cfia/fertiscan-backend/).
https://github.com/ai-cfia/fertiscan-backend/issues/148
=> ADR-19: Python Web Framework

Bytebase/Wins.md, Bytebase/usage-guideline.md, TRAINING.md, adr/006-database-change-management.md, adr/006-review-database-change-management.md
Update of the database ADRs and added the bytebase guideline.
Ref #129
Helps https://github.com/ai-cfia/ailab-datastore/issues/135
=> 129 bytebase guideline
